// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCmZEC7JlzCOGcmkWkQa5uU4muzxRQpg',
    appId: '1:96752491730:web:5758e74f41d0fff5e6a10b',
    messagingSenderId: '96752491730',
    projectId: 'trip-optima-mobile-app',
    authDomain: 'trip-optima-mobile-app.firebaseapp.com',
    storageBucket: 'trip-optima-mobile-app.firebasestorage.app',
    measurementId: 'G-T2G6B35DZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8VrhohOJBMD0kY7QWC7fagDgPnJuorU',
    appId: '1:96752491730:android:6f90e4374b5d5b1ae6a10b',
    messagingSenderId: '96752491730',
    projectId: 'trip-optima-mobile-app',
    storageBucket: 'trip-optima-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1AcToqmtBEUffWfv6HosrRZ0ucrKxs3Q',
    appId: '1:96752491730:ios:8844857b9b1c1dd2e6a10b',
    messagingSenderId: '96752491730',
    projectId: 'trip-optima-mobile-app',
    storageBucket: 'trip-optima-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.tripOptimaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1AcToqmtBEUffWfv6HosrRZ0ucrKxs3Q',
    appId: '1:96752491730:ios:8844857b9b1c1dd2e6a10b',
    messagingSenderId: '96752491730',
    projectId: 'trip-optima-mobile-app',
    storageBucket: 'trip-optima-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.tripOptimaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyCmZEC7JlzCOGcmkWkQa5uU4muzxRQpg',
    appId: '1:96752491730:web:43e6e91666f99374e6a10b',
    messagingSenderId: '96752491730',
    projectId: 'trip-optima-mobile-app',
    authDomain: 'trip-optima-mobile-app.firebaseapp.com',
    storageBucket: 'trip-optima-mobile-app.firebasestorage.app',
    measurementId: 'G-009VVJ0RW8',
  );
}
